name: taro
description: "Taro is a library for loading data from network and saving it to storage to speed up data loading."
version: 2.0.2
repository: https://github.com/koji-1009/taro
issue_tracker: https://github.com/koji-1009/taro/issues
topics:
  - image
  - cache
  - network

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter

  clock: ^1.1.2
  crypto: ^3.0.7
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  build_runner: ^2.0.0
  mockito: ^5.0.0

  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
