name: taro
description: "Taro is a library for loading data from network and saving it to storage to speed up data loading."
version: 1.2.0
homepage: https://github.com/koji-1009/taro

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter

  clock: ^1.0.0
  crypto: ^3.0.0
  image: ^4.0.0
  path_provider: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  build_runner: ^2.0.0
  mockito: ^5.0.0
